version: '3.7'
services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: somepass
      POSTGRES_DB: test
    ports:
      - "9000:5432"
  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - "9042:9042"