version: "3.7"
services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepass
      POSTGRES_DB: test
    ports:
      - "9000:5432"
