# Generated by Django 4.2.7 on 2023-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='wmo_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
