# Generated by Django 4.2.7 on 2023-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_station_wmo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='wmo_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
