# Generated by Django 4.2.4 on 2023-08-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('deduplication_number', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mx')], default='X', max_length=1)),
            ],
            options={
                'unique_together': {('name', 'deduplication_number')},
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('federation', models.CharField(max_length=64)),
                ('parent_federation', models.CharField(blank=True, default='', max_length=64)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('FP', 'Squat-Bench-Deadlift'), ('BD', 'Bench-Deadlift'), ('SD', 'Squat-Deadlift'), ('SB', 'Squat-Bench'), ('SQ', 'Squat'), ('BP', 'Bench'), ('DL', 'Deadlift')], max_length=2)),
                ('equipment', models.CharField(choices=[('R', 'Raw (Bare knees or knee sleeves)'), ('W', 'Wraps (Knee wraps are allowed)'), ('S', 'Single-ply (Equipped, single-ply suits)'), ('M', 'Multi-ply (Equipped, multi-ply suits)'), ('U', 'Unlimited (Equipped, multi-ply suits or rubberized gear)'), ('T', 'Straps (Allowed straps on the deadlift)')], max_length=1)),
                ('drug_tested', models.BooleanField(default=False)),
                ('division', models.CharField(blank=True, default='', max_length=32)),
                ('age', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('age_class', models.CharField(blank=True, default='', max_length=6)),
                ('birth_year_class', models.CharField(blank=True, default='', max_length=6)),
                ('bodyweight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight_class', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deadlift', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('squat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bench_press', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('place', models.PositiveSmallIntegerField(default=0)),
                ('meet_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dots', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='powerlifting.athlete')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='powerlifting.contest')),
            ],
        ),
        migrations.CreateModel(
            name='ContestLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('town', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'unique_together': {('country', 'state', 'town')},
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='powerlifting.contestlocation'),
        ),
    ]
