# Generated by Django 4.2.4 on 2023-08-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerlifting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
