# Generated by Django 5.0 on 2024-01-02 00:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerlifting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestlocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='contestlocation',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
