# Generated by Django 5.0 on 2024-01-07 15:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('town', models.CharField(blank=True, default='', max_length=128)),
                ('loc_coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('weather_station', models.CharField(max_length=30)),
                ('station_coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('distance_to_station', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('population', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('federation', models.CharField(max_length=128)),
                ('average_dots', models.DecimalField(decimal_places=2, max_digits=5)),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimension.location')),
            ],
        ),
    ]
