version: "3.7"
services:
  postgis:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "studentdb", "-U", "student"]
      interval: 5s
      timeout: 3s
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"

  dashboard:
    build: dashboard
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: dashboard.settings
      POSTGRES_HOST: postgis
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
    depends_on:
      postgis:
        condition: service_healthy
        restart: true
    volumes:
      - ./dashboard:/app

volumes:
  pgdata: