version: "3.7"
services:
  postgis:
    image: postgis/postgis:latest
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"

  dashboard:
    build: dashboard
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: dashboard.settings
      POSTGRES_HOST: postgis
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb