version: "3.7"
services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"
