# Generated by Django 5.0 on 2023-12-20 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('federation', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('city_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, max_length=30, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('distance_to_station', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.contest')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_dots', models.DecimalField(decimal_places=2, max_digits=5)),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.contest')),
            ],
        ),
    ]
